version: "3"
services:
  client:
    container_name: web_client
    build:
      context: ./client
      dockerfile: Dockerfile
    image: meetup/client
    ports:
      - "8080:8080"
    expose:
      - "8080"
    volumes:
      - /client
    links:
      - api
  api:
    container_name: web_api
    build:
      context: ./api
      dockerfile: Dockerfile
    image: meetup-project
    ports:
      - "5000:5000"
    expose:
      - "5000"
    volumes:
      - /api
